language: python
python:
  - "2.7"
  - "3.6"
stages:
  - build
  - test
  - deploy
install:
  - pip install -r requirements.txt
jobs:
  include:
    - stage: build
      echo "Build"
    - stage: test
      pytest --pep8
    - stage: deploy
      echo "Deploy"
